-- liquibase formatted sql

-- changeset IrinaSerebryakova:1
CREATE TABLE books (
                      id BIGINT AUTO_INCREMENT PRIMARY KEY,
                      vendor_code VARCHAR(255),
                      title VARCHAR(255),
                      year INT,
                      brand VARCHAR(255),
                      stock INT,
                      price DOUBLE
);

-- changeset IrinaSerebryakova:2
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset IrinaSerebryakova:3
INSERT INTO users (username, password)
VALUES ("Serebrity", "123");

